import '@/styles/globals.css'
import Menu from '@/components/Menu'
import {Poppins} from 'next/font/google'
import Navbar from '@/components/Navbar'

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'], // escolha os pesos que vai usar
    variable: '--font-poppins', // opcional, útil se for usar como uma variável CSS
})

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en" className={poppins.variable}>
            <body className="min-h-screen flex flex-col">
                <Navbar />
                <div className="flex flex-1 min-h-0">
                    <Menu />
                    <main className="flex-1 pt-7 pr-7 pl-7 pb-6">
                        <div className="bg-white h-full rounded-lg shadow-md">
                            <div className="h-full">{children}</div>
                        </div>
                    </main>
                </div>
            </body>
        </html>
    )
}
